#ifndef CONEXION_MEMORIA_H_
#define CONEXION_MEMORIA_H_


typedef enum {
	CREAR_NUEVA_TABLA=10, PROCESO_SUSPENDIDO, DEVOLVER_INDICE_TABLA_NVL2, DEVOLVER_MARCO, LEER, ESCRIBIR, LIBERAR
} inst_memoria;

#endif
//[INST_MEMORIA][SIZE_BUFFER][BUFFER]
//[DEVOLVER_INDICE_TABLA_NVL2][SIZEOF(INT)][TAMAÑO]