#ifndef CONEXION_MEMORIA_H_
#define CONEXION_MEMORIA_H_

//Todos precedidos por [INST_MEMORIA][SIZE_BUFFER]
typedef enum {
	CREAR_NUEVA_TABLA=10, //[PID][TAM_PROCESO]
	PROCESO_SUSPENDIDO, 
	DEVOLVER_INDICE_TABLA_NVL2, // [NRO DE TABLA]
	DEVOLVER_MARCO, //[NRO DE TABLA LVL 2]
	LEER, //[DIRECCION_FISICA]
	ESCRIBIR, //[DIRECCION_FISICA][TAMAÑO_A_ESCRIBIR][DATO_A_ESCRIBIR]
	LIBERAR //[PID]
} inst_memoria;

#endif