#ifndef CONEXION_MEMORIA_H_
#define CONEXION_MEMORIA_H_

//Todos precedidos por [INST_MEMORIA][SIZE_BUFFER]
typedef enum {
	CREAR_NUEVA_TABLA=10, //[PID][TAM_PROCESO] + te mando la tabla
	PROCESO_SUSPENDIDO,//[NRO TABLA]+ te mando bool de confirmacion
	DEVOLVER_INDICE_TABLA_NVL2, // [DIRECCION TABLA 1]][INDICE DE TABLA LVL 1]
	DEVOLVER_MARCO, //[DIRECCION TABLA 2][INDICE DE TABLA LVL 2]
	LEER, //[DIRECCION_FISICA][TAMAÑO_A_LEER]
	ESCRIBIR, //[DIRECCION_FISICA][TAMAÑO_A_ESCRIBIR][DATOS_A_ESCRIBIR]
	LIBERAR //[NRO TABLA]+ te mando bool de confirmacion
} inst_memoria;

#endif